// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: PromisedNeverland_Internet_Clock

#include "ui.h"

lv_obj_t * ui_MainScreen;
lv_obj_t * ui_PanelScreenBorder;
lv_obj_t * ui_ImagePromisedNeverland;
lv_obj_t * ui_PanelHeader;
lv_obj_t * ui_PanelWiFiBar1;
lv_obj_t * ui_PanelWiFiBar2;
lv_obj_t * ui_PanelWiFiBar3;
lv_obj_t * ui_Date;
lv_obj_t * ui_Time;
lv_obj_t * ui_NTPTimer;
lv_obj_t * ui_OWMTimer;
lv_obj_t * ui_Spinner;
lv_obj_t * ui_Sec;
lv_obj_t * ui_IPSeg1;
lv_obj_t * ui_IPSeg2;
lv_obj_t * ui_IPSeg3;
lv_obj_t * ui_IPSeg4;
lv_obj_t * ui_IDNumber1;
lv_obj_t * ui_IDNumber2;
lv_obj_t * ui_PanelFooter;
lv_obj_t * ui_ImageTemp;
lv_obj_t * ui_Temp;
lv_obj_t * ui_ImageHumidity;
lv_obj_t * ui_Humidity;
lv_obj_t * ui_LabelPercent;
lv_obj_t * ui_ImageUVIndex;
lv_obj_t * ui_UVIndex;
lv_obj_t * ui_LabelFPS;
lv_obj_t * ui_FPS;

// event funtions
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_delete(&ui_Start_Screen);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScreenBorder = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelScreenBorder, 176);
    lv_obj_set_height(ui_PanelScreenBorder, 324);
    lv_obj_set_align(ui_PanelScreenBorder, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScreenBorder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelScreenBorder, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelScreenBorder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScreenBorder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScreenBorder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScreenBorder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImagePromisedNeverland = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ImagePromisedNeverland, &ui_img_255117540);
    lv_obj_set_width(ui_ImagePromisedNeverland, LV_SIZE_CONTENT);   /// 172
    lv_obj_set_height(ui_ImagePromisedNeverland, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_x(ui_ImagePromisedNeverland, 0);
    lv_obj_set_y(ui_ImagePromisedNeverland, -11);
    lv_obj_set_align(ui_ImagePromisedNeverland, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePromisedNeverland, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePromisedNeverland, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelHeader = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelHeader, 172);
    lv_obj_set_height(ui_PanelHeader, 18);
    lv_obj_set_x(ui_PanelHeader, 0);
    lv_obj_set_y(ui_PanelHeader, -151);
    lv_obj_set_align(ui_PanelHeader, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelHeader, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWiFiBar1 = lv_obj_create(ui_PanelHeader);
    lv_obj_set_width(ui_PanelWiFiBar1, 5);
    lv_obj_set_height(ui_PanelWiFiBar1, 5);
    lv_obj_set_x(ui_PanelWiFiBar1, -80);
    lv_obj_set_y(ui_PanelWiFiBar1, 4);
    lv_obj_set_align(ui_PanelWiFiBar1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWiFiBar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelWiFiBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelWiFiBar1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWiFiBar1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWiFiBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWiFiBar2 = lv_obj_create(ui_PanelHeader);
    lv_obj_set_width(ui_PanelWiFiBar2, 5);
    lv_obj_set_height(ui_PanelWiFiBar2, 9);
    lv_obj_set_x(ui_PanelWiFiBar2, -74);
    lv_obj_set_y(ui_PanelWiFiBar2, 2);
    lv_obj_set_align(ui_PanelWiFiBar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWiFiBar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelWiFiBar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelWiFiBar2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWiFiBar2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWiFiBar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWiFiBar3 = lv_obj_create(ui_PanelHeader);
    lv_obj_set_width(ui_PanelWiFiBar3, 5);
    lv_obj_set_height(ui_PanelWiFiBar3, 14);
    lv_obj_set_x(ui_PanelWiFiBar3, -68);
    lv_obj_set_y(ui_PanelWiFiBar3, 0);
    lv_obj_set_align(ui_PanelWiFiBar3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelWiFiBar3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelWiFiBar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelWiFiBar3, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWiFiBar3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWiFiBar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_PanelHeader);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, -15);
    lv_obj_set_y(ui_Date, -2);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "31/12/25");
    lv_obj_set_style_text_letter_space(ui_Date, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Date, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date, &ui_font_Witka14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_PanelHeader);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 3);
    lv_obj_set_y(ui_Time, -2);
    lv_obj_set_align(ui_Time, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Time, "00:00");
    lv_obj_set_style_text_letter_space(ui_Time, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time, &ui_font_Witka14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NTPTimer = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_NTPTimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NTPTimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NTPTimer, -63);
    lv_obj_set_y(ui_NTPTimer, -130);
    lv_obj_set_align(ui_NTPTimer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NTPTimer, "6969");
    lv_obj_set_style_text_letter_space(ui_NTPTimer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NTPTimer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NTPTimer, &ui_font_Witka16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OWMTimer = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_OWMTimer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OWMTimer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OWMTimer, -66);
    lv_obj_set_y(ui_OWMTimer, -110);
    lv_obj_set_align(ui_OWMTimer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OWMTimer, "696");
    lv_obj_set_style_text_color(ui_OWMTimer, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OWMTimer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_OWMTimer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_OWMTimer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OWMTimer, &ui_font_Witka16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner = lv_spinner_create(ui_MainScreen, 1000, 90);
    lv_obj_set_width(ui_Spinner, 39);
    lv_obj_set_height(ui_Spinner, 39);
    lv_obj_set_x(ui_Spinner, 60);
    lv_obj_set_y(ui_Spinner, -101);
    lv_obj_set_align(ui_Spinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Spinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Sec = lv_label_create(ui_Spinner);
    lv_obj_set_width(ui_Sec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Sec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Sec, 0);
    lv_obj_set_y(ui_Sec, -2);
    lv_obj_set_align(ui_Sec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Sec, "69");
    lv_obj_set_style_text_letter_space(ui_Sec, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Sec, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Sec, &ui_font_Witka16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPSeg1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_IPSeg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPSeg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPSeg1, -5);
    lv_obj_set_y(ui_IPSeg1, 13);
    lv_obj_set_align(ui_IPSeg1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPSeg1, "696");
    lv_obj_set_style_text_color(ui_IPSeg1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPSeg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IPSeg1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPSeg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPSeg1, &ui_font_Witka16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPSeg2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_IPSeg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPSeg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPSeg2, -1);
    lv_obj_set_y(ui_IPSeg2, 30);
    lv_obj_set_align(ui_IPSeg2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPSeg2, "969");
    lv_obj_set_style_text_color(ui_IPSeg2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPSeg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IPSeg2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPSeg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPSeg2, &ui_font_Witka16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPSeg3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_IPSeg3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPSeg3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPSeg3, 4);
    lv_obj_set_y(ui_IPSeg3, 47);
    lv_obj_set_align(ui_IPSeg3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPSeg3, "696");
    lv_obj_set_style_text_color(ui_IPSeg3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPSeg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IPSeg3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPSeg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPSeg3, &ui_font_Witka16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPSeg4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_IPSeg4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPSeg4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPSeg4, 9);
    lv_obj_set_y(ui_IPSeg4, 64);
    lv_obj_set_align(ui_IPSeg4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPSeg4, "969");
    lv_obj_set_style_text_color(ui_IPSeg4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPSeg4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IPSeg4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IPSeg4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPSeg4, &ui_font_Witka16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IDNumber1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_IDNumber1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IDNumber1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IDNumber1, 59);
    lv_obj_set_y(ui_IDNumber1, 76);
    lv_obj_set_align(ui_IDNumber1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IDNumber1, "6969");
    lv_obj_set_style_text_color(ui_IDNumber1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IDNumber1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IDNumber1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IDNumber1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IDNumber1, &ui_font_Witka16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IDNumber2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_IDNumber2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IDNumber2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IDNumber2, 63);
    lv_obj_set_y(ui_IDNumber2, 59);
    lv_obj_set_align(ui_IDNumber2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IDNumber2, "96");
    lv_obj_set_style_text_color(ui_IDNumber2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IDNumber2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_IDNumber2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_IDNumber2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IDNumber2, &ui_font_Witka16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFooter = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelFooter, 172);
    lv_obj_set_height(ui_PanelFooter, 19);
    lv_obj_set_x(ui_PanelFooter, 0);
    lv_obj_set_y(ui_PanelFooter, 150);
    lv_obj_set_align(ui_PanelFooter, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelFooter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelFooter, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFooter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTemp = lv_img_create(ui_PanelFooter);
    lv_img_set_src(ui_ImageTemp, &ui_img_thermometer_png);
    lv_obj_set_width(ui_ImageTemp, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_ImageTemp, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_ImageTemp, -72);
    lv_obj_set_y(ui_ImageTemp, 0);
    lv_obj_set_align(ui_ImageTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageTemp, 245);

    ui_Temp = lv_label_create(ui_PanelFooter);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp, -119);
    lv_obj_set_y(ui_Temp, -3);
    lv_obj_set_align(ui_Temp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Temp, "69");
    lv_obj_set_style_text_color(ui_Temp, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Temp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Temp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp, &ui_font_Witka14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHumidity = lv_img_create(ui_PanelFooter);
    lv_img_set_src(ui_ImageHumidity, &ui_img_humidity_png);
    lv_obj_set_width(ui_ImageHumidity, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_ImageHumidity, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_ImageHumidity, -19);
    lv_obj_set_y(ui_ImageHumidity, -1);
    lv_obj_set_align(ui_ImageHumidity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHumidity, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImageHumidity, 245);

    ui_Humidity = lv_label_create(ui_PanelFooter);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, -66);
    lv_obj_set_y(ui_Humidity, -3);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Humidity, "69");
    lv_obj_set_style_text_color(ui_Humidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Humidity, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Humidity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity, &ui_font_Witka14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPercent = lv_label_create(ui_PanelFooter);
    lv_obj_set_width(ui_LabelPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPercent, 16);
    lv_obj_set_y(ui_LabelPercent, -1);
    lv_obj_set_align(ui_LabelPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPercent, "%");
    lv_obj_set_style_text_color(ui_LabelPercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPercent, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPercent, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageUVIndex = lv_img_create(ui_PanelFooter);
    lv_img_set_src(ui_ImageUVIndex, &ui_img_1554230089);
    lv_obj_set_width(ui_ImageUVIndex, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_ImageUVIndex, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_ImageUVIndex, 48);
    lv_obj_set_y(ui_ImageUVIndex, 0);
    lv_obj_set_align(ui_ImageUVIndex, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageUVIndex, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageUVIndex, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UVIndex = lv_label_create(ui_PanelFooter);
    lv_obj_set_width(ui_UVIndex, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UVIndex, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UVIndex, 2);
    lv_obj_set_y(ui_UVIndex, -3);
    lv_obj_set_align(ui_UVIndex, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_UVIndex, "69");
    lv_obj_set_style_text_color(ui_UVIndex, lv_color_hex(0xEE82EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UVIndex, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_UVIndex, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_UVIndex, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UVIndex, &ui_font_Witka14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFPS = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_LabelFPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFPS, 53);
    lv_obj_set_y(ui_LabelFPS, -131);
    lv_obj_set_align(ui_LabelFPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFPS, "FPS:");
    lv_obj_set_style_text_letter_space(ui_LabelFPS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelFPS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFPS, &ui_font_Witka10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FPS = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_FPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FPS, -10);
    lv_obj_set_y(ui_FPS, -131);
    lv_obj_set_align(ui_FPS, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_FPS, "69");
    lv_obj_set_style_text_letter_space(ui_FPS, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FPS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FPS, &ui_font_Witka10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_PanelScreenBorder = NULL;
    ui_ImagePromisedNeverland = NULL;
    ui_PanelHeader = NULL;
    ui_PanelWiFiBar1 = NULL;
    ui_PanelWiFiBar2 = NULL;
    ui_PanelWiFiBar3 = NULL;
    ui_Date = NULL;
    ui_Time = NULL;
    ui_NTPTimer = NULL;
    ui_OWMTimer = NULL;
    ui_Spinner = NULL;
    ui_Sec = NULL;
    ui_IPSeg1 = NULL;
    ui_IPSeg2 = NULL;
    ui_IPSeg3 = NULL;
    ui_IPSeg4 = NULL;
    ui_IDNumber1 = NULL;
    ui_IDNumber2 = NULL;
    ui_PanelFooter = NULL;
    ui_ImageTemp = NULL;
    ui_Temp = NULL;
    ui_ImageHumidity = NULL;
    ui_Humidity = NULL;
    ui_LabelPercent = NULL;
    ui_ImageUVIndex = NULL;
    ui_UVIndex = NULL;
    ui_LabelFPS = NULL;
    ui_FPS = NULL;

}
