// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: PromisedNeverland_Internet_Clock

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_PanelScreenBorder;
extern lv_obj_t * ui_ImagePromisedNeverland;
extern lv_obj_t * ui_PanelHeader;
extern lv_obj_t * ui_PanelWiFiBar1;
extern lv_obj_t * ui_PanelWiFiBar2;
extern lv_obj_t * ui_PanelWiFiBar3;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_NTPTimer;
extern lv_obj_t * ui_OWMTimer;
extern lv_obj_t * ui_Spinner;
extern lv_obj_t * ui_Sec;
extern lv_obj_t * ui_IPSeg1;
extern lv_obj_t * ui_IPSeg2;
extern lv_obj_t * ui_IPSeg3;
extern lv_obj_t * ui_IPSeg4;
extern lv_obj_t * ui_IDNumber1;
extern lv_obj_t * ui_IDNumber2;
extern lv_obj_t * ui_PanelFooter;
extern lv_obj_t * ui_ImageTemp;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_ImageHumidity;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_LabelPercent;
extern lv_obj_t * ui_ImageUVIndex;
extern lv_obj_t * ui_UVIndex;
extern lv_obj_t * ui_LabelFPS;
extern lv_obj_t * ui_FPS;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

