// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: PromisedNeverland_Internet_Clock

#include "ui.h"

lv_obj_t * ui_Start_Screen;
lv_obj_t * ui_PanelScreenBorder2;
lv_obj_t * ui_Line0;
lv_obj_t * ui_Line1;
lv_obj_t * ui_Line2;
lv_obj_t * ui_Line2err;
lv_obj_t * ui_Line3;
lv_obj_t * ui_Line4;
lv_obj_t * ui_IPAdd;
lv_obj_t * ui_Line5;
lv_obj_t * ui_Subnet;
lv_obj_t * ui_Line6;
lv_obj_t * ui_Line7;
lv_obj_t * ui_Line8;
lv_obj_t * ui_Line9;
lv_obj_t * ui_Line9err;
lv_obj_t * ui_Line10;
lv_obj_t * ui_Line11;

// event funtions

// build funtions

void ui_Start_Screen_screen_init(void)
{
    ui_Start_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Start_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Start_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Start_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelScreenBorder2 = lv_obj_create(ui_Start_Screen);
    lv_obj_set_width(ui_PanelScreenBorder2, 176);
    lv_obj_set_height(ui_PanelScreenBorder2, 324);
    lv_obj_set_align(ui_PanelScreenBorder2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelScreenBorder2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelScreenBorder2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelScreenBorder2, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelScreenBorder2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScreenBorder2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScreenBorder2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScreenBorder2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line0 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line0, -7);
    lv_obj_set_y(ui_Line0, -113);
    lv_obj_set_align(ui_Line0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line0,
                      "SD Card not found!\n\nThis project requires a SD Card to store\ngeographic & weather data.\n\nInsert a FAT32 formatted SD Card and\nreboot to try again.");
    lv_obj_add_flag(ui_Line0, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Line0, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line1 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line1, -17);
    lv_obj_set_y(ui_Line1, -143);
    lv_obj_set_align(ui_Line1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line1, "Connecting to Wi-Fi, please wait...");
    lv_obj_set_style_text_font(ui_Line1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line2 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line2, -46);
    lv_obj_set_y(ui_Line2, -133);
    lv_obj_set_align(ui_Line2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line2, "Wi-Fi connected!  :)");
    lv_obj_set_style_text_font(ui_Line2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line2err = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line2err, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line2err, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line2err, -7);
    lv_obj_set_y(ui_Line2err, -113);
    lv_obj_set_align(ui_Line2err, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line2err,
                      "Wi-Fi connection attempts timed out :(\n\nCheck network credentials in the code,\n- OR -\nCheck distance to Wi-Fi AP.");
    lv_obj_add_flag(ui_Line2err, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Line2err, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line3 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line3, -46);
    lv_obj_set_y(ui_Line3, -117);
    lv_obj_set_align(ui_Line3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line3, "Wi-Fi network info :");
    lv_obj_set_style_text_font(ui_Line3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line4 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line4, -78);
    lv_obj_set_y(ui_Line4, -107);
    lv_obj_set_align(ui_Line4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line4, "IP :");
    lv_obj_set_style_text_font(ui_Line4, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPAdd = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_IPAdd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPAdd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPAdd, 17);
    lv_obj_set_y(ui_IPAdd, -107);
    lv_obj_set_align(ui_IPAdd, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_IPAdd, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_IPAdd, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_IPAdd, "IP_ADDRESS");
    lv_obj_set_style_text_font(ui_IPAdd, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line5 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line5, -68);
    lv_obj_set_y(ui_Line5, -97);
    lv_obj_set_align(ui_Line5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line5, "Subnet :");
    lv_obj_set_style_text_font(ui_Line5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Subnet = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Subnet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Subnet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Subnet, 37);
    lv_obj_set_y(ui_Subnet, -97);
    lv_obj_set_align(ui_Subnet, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Subnet, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Subnet, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Subnet, "SUBNET");
    lv_obj_set_style_text_font(ui_Subnet, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line6 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line6, -22);
    lv_obj_set_y(ui_Line6, -81);
    lv_obj_set_align(ui_Line6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line6, "Syncing time with NTP server...");
    lv_obj_set_style_text_font(ui_Line6, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line7 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line7, -46);
    lv_obj_set_y(ui_Line7, -71);
    lv_obj_set_align(ui_Line7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line7, "Time synchronized!");
    lv_obj_set_style_text_font(ui_Line7, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line8 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line8, -15);
    lv_obj_set_y(ui_Line8, -55);
    lv_obj_set_align(ui_Line8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line8, "Fetching location & weather data...");
    lv_obj_set_style_text_font(ui_Line8, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line9 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line9, -37);
    lv_obj_set_y(ui_Line9, -45);
    lv_obj_set_align(ui_Line9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line9, "Weather data received! ");
    lv_obj_set_style_text_font(ui_Line9, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line9err = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line9err, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line9err, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line9err, -11);
    lv_obj_set_y(ui_Line9err, -25);
    lv_obj_set_align(ui_Line9err, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line9err,
                      "Could not fetch OWM geo data.\n\nCheck OWM configurtation in code,\n- OR -\nCheck internet connectivity.");
    lv_obj_add_flag(ui_Line9err, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Line9err, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line10 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line10, -42);
    lv_obj_set_y(ui_Line10, -29);
    lv_obj_set_align(ui_Line10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line10, "Loading final assets...");
    lv_obj_set_style_text_font(ui_Line10, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line11 = lv_label_create(ui_Start_Screen);
    lv_obj_set_width(ui_Line11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Line11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Line11, -40);
    lv_obj_set_y(ui_Line11, -13);
    lv_obj_set_align(ui_Line11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Line11, "Starting main display...");
    lv_obj_set_style_text_font(ui_Line11, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Start_Screen_screen_destroy(void)
{
    if(ui_Start_Screen) lv_obj_del(ui_Start_Screen);

    // NULL screen variables
    ui_Start_Screen = NULL;
    ui_PanelScreenBorder2 = NULL;
    ui_Line0 = NULL;
    ui_Line1 = NULL;
    ui_Line2 = NULL;
    ui_Line2err = NULL;
    ui_Line3 = NULL;
    ui_Line4 = NULL;
    ui_IPAdd = NULL;
    ui_Line5 = NULL;
    ui_Subnet = NULL;
    ui_Line6 = NULL;
    ui_Line7 = NULL;
    ui_Line8 = NULL;
    ui_Line9 = NULL;
    ui_Line9err = NULL;
    ui_Line10 = NULL;
    ui_Line11 = NULL;

}
