// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: PromisedNeverland_Internet_Clock

#ifndef UI_START_SCREEN_H
#define UI_START_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Start_Screen
extern void ui_Start_Screen_screen_init(void);
extern void ui_Start_Screen_screen_destroy(void);
extern lv_obj_t * ui_Start_Screen;
extern lv_obj_t * ui_PanelScreenBorder2;
extern lv_obj_t * ui_Line0;
extern lv_obj_t * ui_Line1;
extern lv_obj_t * ui_Line2;
extern lv_obj_t * ui_Line2err;
extern lv_obj_t * ui_Line3;
extern lv_obj_t * ui_Line4;
extern lv_obj_t * ui_IPAdd;
extern lv_obj_t * ui_Line5;
extern lv_obj_t * ui_Subnet;
extern lv_obj_t * ui_Line6;
extern lv_obj_t * ui_Line7;
extern lv_obj_t * ui_Line8;
extern lv_obj_t * ui_Line9;
extern lv_obj_t * ui_Line9err;
extern lv_obj_t * ui_Line10;
extern lv_obj_t * ui_Line11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

